services:
  - type: web
    name: lead-management-system
    env: node
    plan: free
    buildCommand: npm install && npm run build && npm run server:build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: lead-management-db
          property: connectionString
    healthCheckPath: /healthz
